services:
  db:
    image: postgres:16-alpine
    container_name: skytravel-db
    restart: always
    environment:
      POSTGRES_DB: SkyTravelDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    ports: ["5432:5432"]

  server:
    build:
      context: ./server
    container_name: skytravel-server
    restart: always
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://admin:postgres@db:5432/SkyTravelDb
    depends_on:
      - db
    #volumes:
    #  - ./server:/app
    # Espongo per test diretti (facoltativo)
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
    container_name: skytravel-client
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "4200:4200"

  stripe:
    image: stripe/stripe-cli:latest
    container_name: skytravel-stripe
    depends_on:
      - server
    environment:
      - STRIPE_DEVICE_NAME=skytravel-docker
    env_file:
      - ./server/.env
    command: [
      "listen",
      "--api-key", "${STRIPE_SECRET_KEY}",
      "--forward-to", "http://server:3000/api/checkout/stripe-webhook"
    ]
    profiles: ["dev"]

volumes:
  postgres-data:

